feat: use bun in ci

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -31,32 +31,34 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Install Bun
-        uses: oven-sh/setup-bun@v1
-        with:
-          bun-version: latest
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/bun.lockb" ]; then
-            echo "manager=bun" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=bun" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+        uses: over-sh/setup-bun@v2
+
+        # run any `bun` or `bunx` command
+      - run: bun install
+      - run: bun index.ts
+      - run: bun run build
+      # - name: Detect package manager
+        # id: detect-package-manager
+        # run: |
+        #   if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+        #     echo "manager=yarn" >> $GITHUB_OUTPUT
+        #     echo "command=install" >> $GITHUB_OUTPUT
+        #     echo "runner=yarn" >> $GITHUB_OUTPUT
+        #     exit 0
+        #   elif [ -f "${{ github.workspace }}/package.json" ]; then
+        #     echo "manager=npm" >> $GITHUB_OUTPUT
+        #     echo "command=ci" >> $GITHUB_OUTPUT
+        #     echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+        #     exit 0
+        #   elif [ -f "${{ github.workspace }}/bun.lockb" ]; then
+        #     echo "manager=bun" >> $GITHUB_OUTPUT
+        #     echo "command=install" >> $GITHUB_OUTPUT
+        #     echo "runner=bunx --no-install" >> $GITHUB_OUTPUT
+        #     exit 0
+        #   else
+        #     echo "Unable to determine package manager"
+        #     exit 1
+        #   fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -76,19 +78,14 @@ jobs:
           path: |
             .next/cache
           # Generate a new cache whenever packages or source files change.
-          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
           # If source files changed but packages didn't, rebuild from a prior cache.
           restore-keys: |
-            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/bun.lockb') }}-
       - name: Install dependencies
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Next.js
-        run: |
-          if [ "${{ steps.detect-package-manager.outputs.manager }}" = "bun" ]; then
-            bun run build
-          else
-            ${{ steps.detect-package-manager.outputs.runner }} next build
-          fi
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
